var english = {title:"Smygmis troll cave", mainHeader:"Ville Hernesniemi's home page", frontPage:"Front page", programmingPage: "Programming page", hobbyPage:"Hobby page"};
var frontPageEnglishHeader = {siteHeader:"About myself", firstHeader:"My equipment",secondHeader:"Desktop pc",thirdHeader:"Laptop",fourthHeader:"Raspberry pi2 model B",fiftHeader:"Arduino Uno"};
var frontPageEnglishText = {siteHeadText:"I am a second year student at Oulu University of applied sciences. I have a hobby background of programming from nearly ten years. Now I am trying to get a career from the field, and as a part of my own training I have put up these web pages. The purpose of these pages is for me to train web programming, especially JavaScript (Angular) and the Bootstrap framework. I am also going to keep a blog about my programming and hobby projects.", 
							siteFirstText:"I decided to upgrade my old potato of a computer this Christmas. After looking at my old rig and seeing what would still be usable I ended up with memory and hard drive. One week later I ended up with the configuration shown below. While it is not the most powerful pc, it will serve me well and the price I got it for can’t be argued. ",
							siteSecondText:"This two year old Hp pavilion laptop serves me well in school programming projects, as a living room media pc and it is capable enough to do some light gaming on the move. Mainly Hearthstone, Heroes of the storm, Diablo3 and Civ5.",
							siteThirdText:"After being introduced to it at school I totally fell in love the raspberry pi2. This minicomputer offers awesome performance for its credit card size. It has been several years since my last Linux based computer so it’s good to do some catching up on Linux. I’m currently running Raspian Linux on another SD-card, and the retro pi emulation platform from another.",
							siteFourthText:"The Arduino is an easily accessible platform for controlling electronics with a microprocessor. At its core is the very capable 16 MHz Atmel 328p processor, with its I/O pins directly accessible. "};

var programmingPageEnglishHeader = {siteHeader:"Programming/tech blog", firstHeader:"",secondHeader:"",thirdHeader:"",fourthHeader:"",fiftHeader:""};
var programmingPageEnglishText = {siteHeadText:"This is a blog about programming and tech projects.", 
								siteFirstText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
								siteSecondText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
								siteThirdText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
								siteFourthText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English"};
								
var hobbyPageEnglishHeader = {siteHeader:"Hobby blog", firstHeader:"",secondHeader:"",thirdHeader:"",fourthHeader:"",fiftHeader:""};
var hobbyPageEnglishText = {siteHeadText:"This is my hobby blog.", 
							siteFirstText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
							siteSecondText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
							siteThirdText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English",
							siteFourthText:"Lores ipsumi English English English English English English English English diipadaapa English kolkyn plaa English plaa English ipsumi English holkyn kolkyn English plaa plaa English ipsumi English holkyn English"};								
